# Generated by Django 3.2.5 on 2024-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riceplantapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='getintouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=300)),
                ('service', models.CharField(choices=[('service 1', 'SERVICE 1'), ('service 2', 'SERVICE 2')], max_length=200)),
            ],
        ),
    ]
